# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pet.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'pet.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tpet.proto\x12\x03pet\"2\n\nInputEvent\x12\x11\n\thotkey_id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\x04\"0\n\nAudioEvent\x12\x11\n\tamplitude\x18\x01 \x01(\x02\x12\x0f\n\x07is_clap\x18\x02 \x01(\x08\"S\n\x0bScreenFrame\x12\x12\n\njpeg_bytes\x18\x01 \x01(\x0c\x12\r\n\x05width\x18\x02 \x01(\r\x12\x0e\n\x06height\x18\x03 \x01(\r\x12\x11\n\ttimestamp\x18\x04 \x01(\x04\"6\n\x0e\x45motionCommand\x12\x12\n\nemotion_id\x18\x01 \x01(\t\x12\x10\n\x08priority\x18\x02 \x01(\x05\"8\n\x0cSpeechBubble\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x1a\n\x12is_streaming_chunk\x18\x02 \x01(\x08\"=\n\x10PluginRegistered\x12\x13\n\x0bplugin_name\x18\x01 \x01(\t\x12\x14\n\x0c\x63\x61pabilities\x18\x02 \x03(\t\"\xa6\x02\n\nPetMessage\x12&\n\x0binput_event\x18\x01 \x01(\x0b\x32\x0f.pet.InputEventH\x00\x12&\n\x0b\x61udio_event\x18\x02 \x01(\x0b\x32\x0f.pet.AudioEventH\x00\x12(\n\x0cscreen_frame\x18\x03 \x01(\x0b\x32\x10.pet.ScreenFrameH\x00\x12.\n\x0f\x65motion_command\x18\x04 \x01(\x0b\x32\x13.pet.EmotionCommandH\x00\x12*\n\rspeech_bubble\x18\x05 \x01(\x0b\x32\x11.pet.SpeechBubbleH\x00\x12\x32\n\x11plugin_registered\x18\x06 \x01(\x0b\x32\x15.pet.PluginRegisteredH\x00\x42\x0e\n\x0cmessage_typeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pet_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INPUTEVENT']._serialized_start=18
  _globals['_INPUTEVENT']._serialized_end=68
  _globals['_AUDIOEVENT']._serialized_start=70
  _globals['_AUDIOEVENT']._serialized_end=118
  _globals['_SCREENFRAME']._serialized_start=120
  _globals['_SCREENFRAME']._serialized_end=203
  _globals['_EMOTIONCOMMAND']._serialized_start=205
  _globals['_EMOTIONCOMMAND']._serialized_end=259
  _globals['_SPEECHBUBBLE']._serialized_start=261
  _globals['_SPEECHBUBBLE']._serialized_end=317
  _globals['_PLUGINREGISTERED']._serialized_start=319
  _globals['_PLUGINREGISTERED']._serialized_end=380
  _globals['_PETMESSAGE']._serialized_start=383
  _globals['_PETMESSAGE']._serialized_end=677
# @@protoc_insertion_point(module_scope)
