[package]
name = "pet-shell"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.12.1"
cpal = "0.15.2"
crossbeam-channel = "0.5.11"
eframe = "0.28.1"
egui_extras = { version = "0.28.1", features = ["image"] }
image = "0.24.0"
prost = "0.14.4"
prost-types = "0.14.4"
zmq = "0.10.0"

[build-dependencies]
prost-build = "0.14.4"
